omdb:
    key: "7941b866"
---
micronaut:
    application:
        name: omdb-service
    server:
        port: 8081

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
